package view;

import dao.LivroDAO;
import model.dto.Usuario;

import javax.swing.*;
import java.util.Properties;
import model.dto.Avaliacao;
import model.dto.Livro;

public class CadastroLivro extends javax.swing.JFrame {
    
    private Properties properties;
    
    Usuario logado;

    public CadastroLivro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public CadastroLivro(Properties properties, Usuario logado) {
        this();
        this.properties = properties;
        this.logado = logado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notaLivro = new javax.swing.JTextField();
        nomeDoLivro = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        cadastrarLivroButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        managinglife1 = new javax.swing.JLabel();
        nomeAutor = new javax.swing.JTextField();
        romanceRadioButton = new javax.swing.JRadioButton();
        ficcaoRadioButton = new javax.swing.JRadioButton();
        tecnicoRadioButton = new javax.swing.JRadioButton();
        returnpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notaLivro.setToolTipText("");
        notaLivro.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a nota"));
        notaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaLivroActionPerformed(evt);
            }
        });

        nomeDoLivro.setToolTipText("");
        nomeDoLivro.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o nome do livro"));
        nomeDoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoLivroActionPerformed(evt);
            }
        });

        label1.setText("Escolha o Gênero do livro");

        cadastrarLivroButton.setText("Cadastrar");
        cadastrarLivroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivroButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Screenshot_1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N

        managinglife1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        managinglife1.setText("Cadastre um novo Livro");

        nomeAutor.setToolTipText("");
        nomeAutor.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o nome do autor"));
        nomeAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAutorActionPerformed(evt);
            }
        });

        romanceRadioButton.setText("Romance");
        romanceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romanceRadioButtonActionPerformed(evt);
            }
        });

        ficcaoRadioButton.setText("Ficção");

        tecnicoRadioButton.setText("Técnico");

        returnpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/return.png"))); // NOI18N
        returnpage.setLabelFor(cadastrarLivroButton);
        returnpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnpageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(romanceRadioButton)
                            .addGap(28, 28, 28)
                            .addComponent(ficcaoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tecnicoRadioButton))
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeDoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(notaLivro))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(managinglife1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(cadastrarLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnpage)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(managinglife1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnpage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(romanceRadioButton)
                            .addComponent(ficcaoRadioButton)
                            .addComponent(tecnicoRadioButton)))
                    .addComponent(notaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastrarLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        notaLivro.getAccessibleContext().setAccessibleParent(notaLivro);
        nomeDoLivro.getAccessibleContext().setAccessibleParent(nomeDoLivro);
        nomeAutor.getAccessibleContext().setAccessibleParent(nomeAutor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaLivroActionPerformed

    private void nomeDoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoLivroActionPerformed

    private void cadastrarLivroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivroButtonActionPerformed
    
        //atribui ao livro dados simples do livro recebidos do formulario
        Livro livro = new Livro();
        livro.setTitulo(nomeDoLivro.getText());
        livro.setAutor(nomeAutor.getText());
        
        //atribui ao livro o codigo do genero selecionado
        if (romanceRadioButton.isSelected()){
            livro.setIdGenero(1);
        }
        if (ficcaoRadioButton.isSelected()){
            livro.setIdGenero(2);
        }
        if (tecnicoRadioButton.isSelected()){
            livro.setIdGenero(3);
        }
        
        //atribui ao livro o ID do usuario que o cadastrou
        livro.setIdUsuario(logado.getIdUsuario());
        
        try {
            LivroDAO livroDAO = new LivroDAO(properties);
            livroDAO.cadastrar(livro);
            livroDAO.registrar(livro);
            Avaliacao avaliacao = new Avaliacao();
            avaliacao.setNota(Integer.parseInt(notaLivro.getText()));
            avaliacao.setIdLivro(livro.getIdLivro());
            avaliacao.setIdUsuario(logado.getIdUsuario());
            
            System.out.println("Livro cadastrado com sucesso!");

            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
            var ht = new HomeAdminVIEW(properties, logado);
            ht.setVisible(true);
            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog (null, "Erro ao cadastrar o livro/avaliacao");
            e.printStackTrace();
        }

    }//GEN-LAST:event_cadastrarLivroButtonActionPerformed

    private void nomeAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAutorActionPerformed

    private void romanceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romanceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_romanceRadioButtonActionPerformed

    private void returnpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnpageMouseClicked
    var returnHomeAdminVIEW = new HomeAdminVIEW(properties, logado);
    returnHomeAdminVIEW.setVisible(true);
    dispose();
    }//GEN-LAST:event_returnpageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarLivroButton;
    private javax.swing.JRadioButton ficcaoRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private javax.swing.JLabel managinglife1;
    private javax.swing.JTextField nomeAutor;
    private javax.swing.JTextField nomeDoLivro;
    private javax.swing.JTextField notaLivro;
    private javax.swing.JLabel returnpage;
    private javax.swing.JRadioButton romanceRadioButton;
    private javax.swing.JRadioButton tecnicoRadioButton;
    // End of variables declaration//GEN-END:variables
}
